export const getDataBaseUrl = {
    register: '/register',
    login: '/login',
    addBenificial: '/beneficiary_add',
    getBenificial: '/get-all-beneficiaries',
    updateBenificial: '/update-beneficialowner',
    checkBenificialStatus: '/get-beneficiary-status',
    checkBenificialCertify: '/beneficial-ownership',
    deleteBeneficial: '/delete-beneficialowner',
    addVerifiedCustomer: '/customer_add',
    addUnVerifiedCustomer: '/customer_add',
    customers: '/customers',
    updateCustomer: '/customer_update',
    addFunding: '/funding-sources',
    getFundings: '/get-funding-sources',
    deleteFunding: '/remove',
    updateFunding: '/update-funding-source',
    fundingBalance: '/balance',
    balanceCheck: '/balance',
    getAllConnectedCustomers: '/list-account',
    getAllConnectedUsers: '/register_user_list',
    addFund: '/add-fund',
    tranferFund: '/transfer-amount',
    createConnectedAccount: '/accounts',
    frontFileUpload:'/file-upload',
    payingoutFund:'/payouts',
    getTransactionsAll: '/all-transaction',
    getAllTransactionHistory: '/get-trxn-history',
    getTransactionsPerticular: '/transaction',
    getWallet: '/get-wallet',
    fetchAccDetail: '/retrieve-account',
    raiseInvoice: '/raise-invoice',
    raiseRequest: '/raise-request',
    getNotification: '/get-notification',
    getPaymentRequest: '/get-payment-request',
    getSentInvoiceRequest: '/sent-invoices',
    getBankListRequest: '/get-institutions',
    getPlaidAuthRequest: '/plaid_auth',
    getPlaidTokenRequest: '/token_exchange',
    getPlaidBankAccountToken: '/bank_account_token_create',
    getPlaidAccountIdRequest: '/account_id_generate',
    getACHCustomer: '/ach-customer',
    getBankAccounts: '/get-bank-accounts',
    getACHCustomerBankAccount: '/ach_customer_bank_account',
    checkCustomerRequest: '/check-customer-added',
};
